# Generated by Django 5.2.2 on 2025-06-12 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resolution',
            name='response',
        ),
        migrations.AddField(
            model_name='resolution',
            name='comments',
            field=models.TextField(default='', help_text='response to complaint', max_length=255, verbose_name='Response'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resolution',
            name='is_reviewed',
            field=models.BooleanField(default=False, help_text='Whether the resolution has been reviewed', verbose_name='Is Reviewed'),
        ),
        migrations.AlterField(
            model_name='resolution',
            name='resolved_by',
            field=models.ForeignKey(help_text='The admin who resolved the complaint', on_delete=django.db.models.deletion.CASCADE, related_name='resolved_resolutions', to='core.adminprofile', verbose_name='Resolved by'),
        ),
        migrations.AlterField(
            model_name='resolution',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='The admin who reviewed the resolution', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_resolutions', to='core.adminprofile', verbose_name='Reviewed by'),
        ),
    ]
