# Generated by Django 5.2.2 on 2025-06-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='office',
            field=models.CharField(choices=[('FINANCE_DEPARTMENT', 'Finance Department'), ('CISCO_LAB', 'Cisco Lab'), ('REGISTRAR_OFFICE', 'Registrar Office'), ('FACULTY', 'Faculty'), ('OTHER', 'Other')], max_length=50),
        ),
    ]
