# Generated by Django 5.2 on 2025-05-28 09:11

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='secondary_role',
            field=models.CharField(blank=True, choices=core.models.UserRole.choices, help_text='Optional second role for users with multiple roles', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=core.models.UserRole.choices, default=core.models.UserRole['STUDENT'], help_text='Role of the user in the system', max_length=100),
        ),
    ]
