# Generated by Django 5.2.2 on 2025-06-10 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customuser_secondary_role_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='complaint',
            field=models.ForeignKey(default='', help_text='The complaint this attachment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.complaint', verbose_name='Complaint'),
            preserve_default=False,
        ),
    ]
