# Generated by Django 5.2 on 2025-06-02 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customuser_secondary_role_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='course',
            field=models.ForeignKey(default='', help_text='The course for which a complaint was submitted', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.course', verbose_name='Course'),
            preserve_default=False,
        ),
    ]
