# Generated by Django 5.2.2 on 2025-06-25 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_studentprofile_student_number_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='studentprofile',
            name='unique_student_number',
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='faculty',
            field=models.CharField(choices=[('ICT', 'ICT'), ('BMS', 'BMS'), ('BOTH', 'Both ICT and BMS')], max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='faculty',
            field=models.CharField(choices=[('ICT', 'ICT'), ('BMS', 'BMS'), ('BOTH', 'Both ICT and BMS')], max_length=100),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('lecturer', 'code', 'semester', 'year'), name='unique_course_per_lecturer'),
        ),
    ]
