# Generated by Django 5.2.2 on 2025-06-26 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_studentprofile_unique_student_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resolution',
            name='comments',
            field=models.TextField(help_text='response to complaint', verbose_name='Response'),
        ),
    ]
