# Generated by Django 5.2 on 2025-06-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_complaint_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Escalated', 'Escalated')], default='Open', help_text='The status of the complaint', max_length=255, verbose_name='Status'),
        ),
    ]
