# Generated by Django 5.2.1 on 2025-06-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_adminprofile_user_alter_lecturerprofile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='slug',
            field=models.SlugField(editable=False, max_length=255, verbose_name='Category Slug'),
        ),
    ]
