# Generated by Django 5.2.2 on 2025-06-10 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_complaint_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='admins',
            field=models.ManyToManyField(blank=True, help_text='Admins responsible for this category', related_name='categories', to='core.adminprofile', verbose_name='Admins'),
        ),
        migrations.AddField(
            model_name='complaintassignment',
            name='message',
            field=models.TextField(blank=True, help_text='Message sent along with the assignment', null=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='office',
            field=models.CharField(choices=[('FINANCE_DEPARTMENT', 'Finance Department'), ('CISCO_LAB', 'Cisco Lab'), ('REGISTRAR_OFFICE', 'Registrar Office'), ('FACULTY', 'Faculty')], max_length=50),
        ),
        migrations.AlterField(
            model_name='complaintassignment',
            name='staff',
            field=models.ForeignKey(help_text='The staff member assigned to the complaint', limit_choices_to={'role__in': ['Lecturer', 'Admin', 'Complaint Coordinator']}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_complaints', to=settings.AUTH_USER_MODEL, verbose_name='Staff'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='staff',
            field=models.ForeignKey(help_text='The staff member to whom the reminder is sent', limit_choices_to={'role__in': ['Lecturer', 'Admin', 'Complaint Coordinator']}, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL, verbose_name='Staff'),
        ),
        migrations.AlterField(
            model_name='resolution',
            name='staff',
            field=models.ForeignKey(help_text='The staff member who resolved the complaint', limit_choices_to={'role__in': ['Lecturer', 'Admin', 'Complaint Coordinator']}, on_delete=django.db.models.deletion.CASCADE, related_name='resolutions', to=settings.AUTH_USER_MODEL, verbose_name='Staff'),
        ),
    ]
