# Generated by Django 5.2.2 on 2025-06-10 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_attachment_complaint'),
        ('core', '0007_category_admins_complaintassignment_message_and_more'),
    ]

    operations = [
    ]
